/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#005da7",
        "primary-container": "#2976c7",
        "primary-fixed": "#d4e3ff",
        "primary-fixed-dim": "#a4c9ff",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#001c39",
        "on-primary-fixed-variant": "#004883",
        "on-primary-container": "#fdfcff",
        "inverse-primary": "#a4c9ff",

        secondary: "#705d00",
        "secondary-container": "#fdd73b",
        "secondary-fixed": "#ffe173",
        "secondary-fixed-dim": "#e8c426",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#221b00",
        "on-secondary-fixed-variant": "#554500",
        "on-secondary-container": "#715d00",

        tertiary: "#006b28",
        "tertiary-container": "#21863b",
        "tertiary-fixed": "#96f89f",
        "tertiary-fixed-dim": "#7bdb85",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#002107",
        "on-tertiary-fixed-variant": "#00531d",
        "on-tertiary-container": "#f7fff2",

        "sky-blue": "#4a90e2",
        "sunny-yellow": "#fdd73b",
        "soft-green": "#96f89f",
        "soft-pink": "#fce4ec",
        "soft-purple": "#f3e5f5",

        background: "#fbf9f8",
        surface: "#fbf9f8",
        "surface-dim": "#dbd9d9",
        "surface-bright": "#fbf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3f3",
        "surface-container": "#efeded",
        "surface-container-high": "#eae8e7",
        "surface-container-highest": "#e4e2e2",
        "surface-variant": "#e4e2e2",
        "on-surface": "#1b1c1c",
        "on-surface-variant": "#414751",

        "on-background": "#1b1c1c",
        outline: "#717783",
        "outline-variant": "#c1c7d3",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f2f0f0",

        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        sans: ["Tajawal", "sans-serif"],
        headline: ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Tajawal", "sans-serif"],
        "label-md": ["Tajawal", "sans-serif"],
        "body-lg": ["Tajawal", "sans-serif"],
        "body-md": ["Tajawal", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-xl-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
      },
      borderRadius: {
        xl: "1.5rem",
        "2xl": "2rem",
        "3xl": "3rem",
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "64px",
        "margin-mobile": "16px",
        gutter: "24px",
        xl: "80px",
        lg: "48px",
        md: "24px",
        sm: "12px",
        base: "8px",
        xs: "4px",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
}
